### ISSUE TITLE
Look for SVM library for sentiment NER analysis

### ISSUE THREAD

**Issue by Svetuf** [Svetuf/CSC_Sentiment_Russian_NER#17]
Make an overview of SVM libraries exclude scikit-learn, because this library does not working with big amounts of data

**Comment by margaritatsobenko** [comment]
LIBSVM (Library for Support Vector Machines)

[https://pypi.org/project/libsvm/](https://pypi.org/project/libsvm/)

[https://github.com/cjlin1/libsvm](https://github.com/cjlin1/libsvm)

[https://stackoverflow.com/questions/4214868/an-example-using-python-bindings-for-svm-library-libsvm](https://stackoverflow.com/questions/4214868/an-example-using-python-bindings-for-svm-library-libsvm)

$SVM^{struct}$ Python

[https://www.cs.cornell.edu/people/tj/svm_light/svm_struct.html](https://www.cs.cornell.edu/people/tj/svm_light/svm_struct.html)

ThunderSVM: A Fast SVM Library on GPUs and CPUs

[https://pythonrepo.com/repo/Xtra-Computing-thundersvm-python-deep-learning](https://pythonrepo.com/repo/Xtra-Computing-thundersvm-python-deep-learning)

[https://github.com/Xtra-Computing/thundersvm](https://github.com/Xtra-Computing/thundersvm)

[https://medium.com/analytics-vidhya/how-to-install-and-run-thundersvm-in-google-colab-de1fe49eef85](https://medium.com/analytics-vidhya/how-to-install-and-run-thundersvm-in-google-colab-de1fe49eef85)
